### ISSUE TITLE
Spring Data JPA를 활용한 insert, update 구현 방법에 대한 논의

### ISSUE THREAD

**Issue by Oodls** [FISub/backend#5]
- JPQL를 활용한 방법
![image](https://github.com/user-attachments/assets/de8e50c1-2beb-4ea1-90f8-aa08db3d0dec)

- NativeQuery를 활용한 방법
![image](https://github.com/user-attachments/assets/70c6475a-f608-4319-878a-70013048338f)

- save() 함수를 사용한 방법
![image](https://github.com/user-attachments/assets/fec0bde1-593c-419e-af10-1f97acdcd245)

샘플 코드 리뷰 후 사용 방식 결정 및 통일

**간단한 쿼리 - save()
조인 등의 복잡한 쿼리 - NativeQuery 
방식으로 결정**

**Comment by Been980804** [comment]
Native Query & Save()

**Comment by Oodls** [comment]
간단한 쿼리 - save()
조인 등의 복잡한 쿼리 - NativeQuery
방식으로 결정
