### ISSUE TITLE
회원 정보 관련 문제 수정 issue

### ISSUE THREAD

**Issue by Oodls** [FISub/backend#52]
- 회원 정보 수정 시 세션-쿠키 방식으로 로그인 중인 회원 검사 하고 있지만, 민감한 정보 수정 과정이므로 password 검증 로직 구현 
- 회원 정보 수정 시 암호화된 비밀번호가 dto로 넘어가는 부분 수정

**Comment by Been980804** [comment]
password 검증 로직이라는게 어떤 의미인가요?

**Comment by Oodls** [comment]
> password 검증 로직이라는게 어떤 의미인가요?

정보 수정시에 password를 넣는데 그게 로그인 중인 사용자의 password와 일치하면 변경 하도록 하는 것 입니다.
